import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en' | 'zh';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    nav_home: 'Inicio',
    nav_services: 'Servicios',
    nav_portfolio: 'Portafolio',
    nav_about: 'Nosotros',
    portfolio_hero_title: 'IMPACTO // ESTRATÉGICO',
    portfolio_hero_desc: 'Casos reales de disrupción digital. No decoramos, construimos sistemas que dominan mercados y exigen atención.',
    portfolio_filter_all: 'Todos',
    portfolio_filter_web: 'Ingeniería Web',
    portfolio_filter_marketing: 'Marketing',
    portfolio_filter_branding: 'Branding',
    portfolio_view_project: 'Ver Caso de Éxito',
    portfolio_challenge: 'El Desafío',
    portfolio_solution: 'La Solución Brutal',
    portfolio_result: 'El Resultado',
    hero_line_1: 'Transforma',
    hero_line_2: 'tu visión en',
    hero_line_3: 'excelencia',
    hero_line_4: 'digital',
    hero_desc: 'Potenciando marcas con diseños innovadores y estrategias comerciales a medida. Estructura minimalista, resultados brutalmente efectivos.',
    hero_btn_view: 'Ver Portafolio',
    hero_btn_reels: 'Ver Reels',
    capabilities: 'Capacidades // 2024',
    engineering: 'Ingeniería',
    excellence: 'de Excelencia.',
    contact_title_prefix: 'CONTÁCTA',
    contact_title_highlight: 'NOS',
    contact_desc: '¿Listo para irrumpir en el mercado? Envíanos tu visión. Sin adornos, solo resultados.',
    contact_ai_title: 'Estrategia IA del Laboratorio',
    contact_ai_placeholder: 'TU VISIÓN AQUÍ...',
    contact_ai_btn: 'OBTENER VERDAD BRUTAL',
    workflow_title_prefix: 'EL',
    workflow_title_highlight: 'LABORATORIO',
    workflow_title_suffix: 'EN FLUJO',
    method: 'Nuestro Método',
    marquee_1: 'Diseño Basado en Datos //',
    marquee_2: 'Estrategia Disruptiva //',
    marquee_3: 'Estructura Pura //',
    marquee_4: 'Excelencia Digital //',
    stat_projects: 'Proyectos Completados',
    stat_experience: 'Años de Experiencia',
    stat_clients: 'Clientes Globales',
    process_1_title: 'Descubrimiento',
    process_1_desc: 'Inmersión profunda en el ADN de su marca y el panorama del mercado.',
    process_2_title: 'Estrategia',
    process_2_desc: 'Elaboración de un plan brutalista para la máxima disrupción del mercado.',
    process_3_title: 'Ejecución',
    process_3_desc: 'Diseño de alta fidelidad e implementación de desarrollo robusto.',
    process_4_title: 'Lanzamiento',
    process_4_desc: 'Optimización y escalado continuos para un impacto global.',
    contact_danger: 'Zona de Peligro',
    contact_id: 'Identificador',
    contact_coord: 'Coordenadas',
    contact_msg: 'Mensaje',
    contact_name_placeholder: 'NOMBRE...',
    contact_email_placeholder: 'CORREO...',
    contact_brief_placeholder: 'BREVE...',
    contact_btn: 'Iniciar Contacto',
    brand_identity: 'Identidad de Marca // Arquitectura',
    brand_download: 'Descargar Kit de Marca.zip',
    spec_dna: 'Colores Principales // ADN Principal',
    spec_palette: 'Colores Secundarios // Paleta de Identidad',
    spec_design: 'Diseño',
    spec_marketing: 'Marketing',
    spec_dev: 'Programación',
    team_title_prefix: 'CONOCE AL',
    team_title_highlight: 'EQUIPO',
    team_lead: 'Líder de Diseño',
    team_executive: 'Ejecutivo',
    team_dev: 'Desarrollador Frontend',
    team_marketing: 'Marketing',
    team_marketing_exec: 'Ejecutiva de Marketing',
    package_label: 'Paquete',
    package_platforms: 'Alcance de Plataformas:',
    package_content: 'Piezas de Contenido Mensuales:',
    package_google: 'Gestión Google:',
    package_investment: 'Inversión en Pauta:',
    package_monthly_access: 'Acceso Mensual al Laboratorio',
    impact: 'Nuestro Impacto',
    portfolio_tag: 'Estudio de Caso',
    services_hero_title: 'INGENIERÍA // SOLUCIONES',
    services_hero_desc: 'Sistemas digitales de alto rendimiento diseñados para la dominación del mercado. Sin ornamentos innecesarios, solo pura eficiencia arquitectónica.',
    services_stack_title: 'NUESTRO STACK TÉCNICO',
    services_stack_desc: 'Herramientas de vanguardia para resultados disruptivos.',
    services_cta_title: '¿Listo para <span class="italic">escalar?</span>',
    services_cta_btn: 'Iniciar Sinc_Sistema',
    pkg_web_title: 'Paquete',
    pkg_web_params: 'Parámetros De Página Web',
    pkg_web_1_name: 'Kit De Crecimiento',
    pkg_web_2_name: 'Potencial Pro',
    pkg_web_1_feat_1: '5-15 páginas con blog, optimizada para pasarela de pagos.',
    pkg_web_1_feat_2: 'Estructura optimizada y entrega en 2 semanas.',
    pkg_web_1_feat_3: 'Backups semanales, CDN y soporte prioritario.',
    pkg_web_1_feat_4: 'Ideal para E-commerce, servicios y captación de leads.',
    pkg_web_1_feat_5: 'Correos corporativos, SSL ilimitado y ancho de banda sin restricciones.',
    pkg_web_1_feat_6: 'Hosting en Hostinger y dominio gratis (1er año).',
    pkg_web_1_feat_7: 'Plugins esenciales de caché, respaldos y SEO on-page incluidos.',
    pkg_web_1_feat_8: 'Sesión de revisión en vivo antes de la puesta en marcha definitiva.',
    pkg_web_2_feat_1: 'Más de 15 páginas a medida con arquitectura de alta capacidad.',
    pkg_web_2_feat_2: 'Gestión de hasta 5,000 productos.',
    pkg_web_2_feat_3: 'Panel de cliente, entorno de pruebas (staging) y QA dedicado.',
    pkg_web_2_feat_4: 'Optimización para tráfico pesado y entrega en ciclos de dos semanas.',
    pkg_web_2_feat_5: 'Correos corporativos, SSL ilimitado y ancho de banda sin restricciones.',
    pkg_web_2_feat_6: 'Hosting en Hostinger y dominio gratis (1er año).',
    pkg_web_2_feat_7: 'Plugins esenciales de caché, respaldos y SEO on-page incluidos.',
    pkg_web_2_feat_8: 'Sesión de revisión en vivo antes de la puesta en marcha definitiva.',
    pkg_a_name: 'Acelerador Pro',
    pkg_a_platforms: 'Instagram, Facebook y Google (Search + Maps).',
    pkg_a_content: '16 piezas (8 Estáticas, 8 Animadas) + 12 Historias interactivas.',
    pkg_a_google: 'Optimización de perfil de negocio, respuesta a reseñas y 4 publicaciones mensuales en Maps.',
    pkg_a_invest: '$1,500 USD (Ad Spend). Alcance: 60,280 a 72,140 impresiones.',
    pkg_b_name: 'Dominio Total',
    pkg_b_platforms: 'Instagram, Facebook, TikTok y Google (Search + Maps).',
    pkg_b_content: '28 piezas (12 Estáticas, 16 Animadas) + 20 Historias interactivas.',
    pkg_b_google: 'Gestión premium con actualización de catálogo y seguimiento de ranking local.',
    pkg_b_invest: '$3,000 USD (Ad Spend). Alcance: 144,200 a 165,100 impresiones.',
    pkg_c_name: 'Omnicanal Elite',
    pkg_c_platforms: 'Instagram, Facebook, TikTok, LinkedIn y Google (Search + Maps).',
    pkg_c_content: '45 piezas (20 Estáticas, 25 Animadas) + 30 Historias interactivas.',
    pkg_c_google: 'Auditoría técnica continua y optimización avanzada para alta competencia.',
    pkg_c_invest: '$5,000 USD (Ad Spend). Alcance: 435,700 a 655,700 impresiones.',
    about_hero_title: 'NUESTRA // HISTORIA',
    about_hero_desc: 'Nacidos de la necesidad de romper el ruido digital. Drekam Lab no es una agencia, es un sistema de ingeniería para el éxito de marca.',
    about_origin_title: 'EL ORIGEN DEL CAOS CONTROLADO',
    about_origin_p1: 'Fundado en 2006, Drekam Lab surgió como una respuesta brutalista al diseño genérico. Creemos que la estructura debe seguir a la función, pero la función debe dominar el mercado.',
    about_origin_p2: 'Lo que comenzó como un pequeño taller de código en un sótano se ha convertido en un laboratorio global de disrupción digital.',
    about_milestone_1_year: '2006',
    about_milestone_1_text: 'Iniciación del núcleo del sistema.',
    about_milestone_2_year: '2012',
    about_milestone_2_text: 'Expansión omnicanal completada.',
    about_milestone_3_year: '2018',
    about_milestone_3_text: 'Dominación del mercado regional.',
    about_milestone_4_year: '2024',
    about_milestone_4_text: 'Integración total de IA Generativa.',
    about_achievements_title: 'LOGROS DEL SISTEMA',
  },
  en: {
    nav_home: 'Home',
    nav_services: 'Services',
    nav_portfolio: 'Portfolio',
    nav_about: 'About',
    portfolio_hero_title: 'STRATEGIC // IMPACT',
    portfolio_hero_desc: 'Real cases of digital disruption. We don’t decorate, we build systems that dominate markets and command attention.',
    portfolio_filter_all: 'All',
    portfolio_filter_web: 'Web Engineering',
    portfolio_filter_marketing: 'Marketing',
    portfolio_filter_branding: 'Branding',
    portfolio_view_project: 'View Case Study',
    portfolio_challenge: 'The Challenge',
    portfolio_solution: 'The Brutal Solution',
    portfolio_result: 'The Result',
    hero_line_1: 'Transform',
    hero_line_2: 'your vision into',
    hero_line_3: 'digital',
    hero_line_4: 'excellence',
    hero_desc: 'Empowering brands with innovative designs and tailored business strategies. Minimalist structure, brutally effective results.',
    hero_btn_view: 'View Portfolio',
    hero_btn_reels: 'Watch Reels',
    capabilities: 'Capabilities // 2024',
    engineering: 'Engineering',
    excellence: 'Excellence.',
    contact_title_prefix: 'CONTACT',
    contact_title_highlight: 'US',
    contact_desc: 'Ready to disrupt the market? Send us your vision. No fluff, just results.',
    contact_ai_title: 'Lab AI Strategy',
    contact_ai_placeholder: 'YOUR VISION HERE...',
    contact_ai_btn: 'GET BRUTAL TRUTH',
    workflow_title_prefix: 'THE',
    workflow_title_highlight: 'LAB',
    workflow_title_suffix: 'WORKFLOW',
    method: 'Our Method',
    marquee_1: 'Data Driven Design //',
    marquee_2: 'Disruptive Strategy //',
    marquee_3: 'Raw Structure //',
    marquee_4: 'Digital Excellence //',
    stat_projects: 'Projects Completed',
    stat_experience: 'Experience Years',
    stat_clients: 'Global Clients',
    process_1_title: 'Discovery',
    process_1_desc: 'Deep dive into your brand DNA and market landscape.',
    process_2_title: 'Strategy',
    process_2_desc: 'Crafting a brutalist plan for maximum market disruption.',
    process_3_title: 'Execution',
    process_3_desc: 'High-fidelity design and robust development implementation.',
    process_4_title: 'Launch',
    process_4_desc: 'Continuous optimization and scaling for global impact.',
    contact_danger: 'Danger Zone',
    contact_id: 'Identificator',
    contact_coord: 'Coordinates',
    contact_msg: 'Message',
    contact_name_placeholder: 'NAME...',
    contact_email_placeholder: 'EMAIL...',
    contact_brief_placeholder: 'BRIEF...',
    contact_btn: 'Initiate Contact',
    brand_identity: 'Brand Identity // Architecture',
    brand_download: 'Download Brand Kit.zip',
    spec_dna: 'Core Colors // Core DNA',
    spec_palette: 'Secondary Colors // Identity Palette',
    spec_design: 'Design',
    spec_marketing: 'Marketing',
    spec_dev: 'Programming',
    team_title_prefix: 'MEET THE',
    team_title_highlight: 'TEAM',
    team_lead: 'Lead Designer',
    team_executive: 'Executive',
    team_dev: 'Frontend Dev',
    team_marketing: 'Marketing',
    team_marketing_exec: 'Marketing Executive',
    package_label: 'Package',
    package_platforms: 'Platform Reach:',
    package_content: 'Monthly Content Pieces:',
    package_google: 'Google Management:',
    package_investment: 'Ad Investment:',
    package_monthly_access: 'Monthly Lab Access',
    impact: 'Our Impact',
    portfolio_tag: 'Case Study',
    services_hero_title: 'ENGINEERING // SOLUTIONS',
    services_hero_desc: 'High-performance digital systems engineered for market dominance. No unnecessary ornaments, just pure architectural efficiency.',
    services_stack_title: 'OUR TECH STACK',
    services_stack_desc: 'Cutting-edge tools for disruptive results.',
    services_cta_title: 'Ready to <span class="italic">scale?</span>',
    services_cta_btn: 'Initiate System_Sync',
    pkg_web_title: 'Package',
    pkg_web_params: 'Web Page Parameters',
    pkg_web_1_name: 'Growth Kit',
    pkg_web_2_name: 'Pro Potential',
    pkg_web_1_feat_1: '5-15 custom pages with blog, optimized for payment gateway.',
    pkg_web_1_feat_2: 'Optimized structure and 2-week delivery.',
    pkg_web_1_feat_3: 'Weekly backups, CDN, and priority support.',
    pkg_web_1_feat_4: 'Ideal for E-commerce, services, and lead generation.',
    pkg_web_1_feat_5: 'Corporate emails, unlimited SSL, and unrestricted bandwidth.',
    pkg_web_1_feat_6: 'Hosting on Hostinger and free domain (1st year).',
    pkg_web_1_feat_7: 'Essential cache, backup, and on-page SEO plugins included.',
    pkg_web_1_feat_8: 'Live review session before final deployment.',
    pkg_web_2_feat_1: 'Over 15 custom pages with high-capacity architecture.',
    pkg_web_2_feat_2: 'Management for up to 5,000 products.',
    pkg_web_2_feat_3: 'Client panel, staging environment, and dedicated QA.',
    pkg_web_2_feat_4: 'Heavy traffic optimization and delivery in two-week cycles.',
    pkg_web_2_feat_5: 'Corporate emails, unlimited SSL, and unrestricted bandwidth.',
    pkg_web_2_feat_6: 'Hosting on Hostinger and free domain (1st year).',
    pkg_web_2_feat_7: 'Essential cache, backup, and on-page SEO plugins included.',
    pkg_web_2_feat_8: 'Live review session before final deployment.',
    pkg_a_name: 'Pro Accelerator',
    pkg_a_platforms: 'Instagram, Facebook and Google (Search + Maps).',
    pkg_a_content: '16 pieces (8 Static, 8 Animated) + 12 Interactive Stories.',
    pkg_a_google: 'Business profile optimization, review replies and 4 monthly posts on Maps.',
    pkg_a_invest: '$1,500 USD (Ad Spend). Reach: 60,280 to 72,140 impressions.',
    pkg_b_name: 'Total Domain',
    pkg_b_platforms: 'Instagram, Facebook, TikTok and Google (Search + Maps).',
    pkg_b_content: '28 pieces (12 Static, 16 Animated) + 20 Interactive Stories.',
    pkg_b_google: 'Premium management with catalog updates and local ranking tracking.',
    pkg_b_invest: '$3,000 USD (Ad Spend). Reach: 144,200 to 165,100 impressions.',
    pkg_c_name: 'Elite Omnichannel',
    pkg_c_platforms: 'Instagram, Facebook, TikTok, LinkedIn and Google (Search + Maps).',
    pkg_c_content: '45 pieces (20 Static, 25 Animated) + 30 Interactive Stories.',
    pkg_c_google: 'Continuous technical audit and advanced optimization for high competition.',
    pkg_c_invest: '$5,000 USD (Ad Spend). Reach: 435,700 to 655,700 impressions.',
    about_hero_title: 'OUR // STORY',
    about_hero_desc: 'Born from the need to break through digital noise. Drekam Lab is not an agency, it is an engineering system for brand success.',
    about_origin_title: 'THE ORIGIN OF CONTROLLED CHAOS',
    about_origin_p1: 'Founded in 2006, Drekam Lab emerged as a brutalist response to generic design. We believe structure must follow function, but function must dominate the market.',
    about_origin_p2: 'What started as a small basement code workshop has evolved into a global digital disruption lab.',
    about_milestone_1_year: '2006',
    about_milestone_1_text: 'System core initiation.',
    about_milestone_2_year: '2012',
    about_milestone_2_text: 'Omnichannel expansion completed.',
    about_milestone_3_year: '2018',
    about_milestone_3_text: 'Regional market domination.',
    about_milestone_4_year: '2024',
    about_milestone_4_text: 'Total GenAI integration.',
    about_achievements_title: 'SYSTEM ACHIEVEMENTS',
  },
  zh: {
    nav_home: '首页',
    nav_services: '服务',
    nav_portfolio: '作品集',
    nav_about: '关于我们',
    portfolio_hero_title: '战略 // 影响力',
    portfolio_hero_desc: '数字颠覆的真实案例。我们不只是装饰，我们构建主导市场并吸引注意力的系统。',
    portfolio_filter_all: '全部',
    portfolio_filter_web: '网络工程',
    portfolio_filter_marketing: '营销',
    portfolio_filter_branding: '品牌',
    portfolio_view_project: '查看案例研究',
    portfolio_challenge: '挑战',
    portfolio_solution: '残酷解决方案',
    portfolio_result: '结果',
    hero_line_1: '将您的',
    hero_line_2: '愿景转化为',
    hero_line_3: '数字',
    hero_line_4: '卓越',
    hero_desc: '通过创新设计和量身定制的商业策略赋能品牌。极简结构，极具成效。',
    hero_btn_view: '作品集',
    hero_btn_reels: '查看演示',
    capabilities: '能力 // 2024',
    engineering: '工程',
    excellence: '卓越。',
    contact_title_prefix: '联系',
    contact_title_highlight: '我们',
    contact_desc: '准备好颠覆市场了吗？向我们发送您的愿景。没有废话，只有结果。',
    contact_ai_title: '实验室 AI 策略',
    contact_ai_placeholder: '在这里输入您的愿景...',
    contact_ai_btn: '获取残酷真相',
    workflow_title_prefix: '',
    workflow_title_highlight: '实验室',
    workflow_title_suffix: '工作流',
    method: '我们的方法',
    marquee_1: '数据驱动设计 //',
    marquee_2: '颠覆性策略 //',
    marquee_3: '原始结构 //',
    marquee_4: '数字卓越 //',
    stat_projects: '完成项目',
    stat_experience: '经验年限',
    stat_clients: '全球客户',
    process_1_title: '探索阶段',
    process_1_desc: '深入了解您的品牌 DNA 和市场格局。',
    process_2_title: '战略制定',
    process_2_desc: '制定极致的市场颠覆计划。',
    process_3_title: '高效执行',
    process_3_desc: '高保真设计和稳健的开发实现。',
    process_4_title: '正式发布',
    process_4_desc: '持续优化和扩展，以实现全球影响力。',
    contact_danger: '危险区域',
    contact_id: '标识符',
    contact_coord: '坐标',
    contact_msg: '留言',
    contact_name_placeholder: '姓名...',
    contact_email_placeholder: '邮箱...',
    contact_brief_placeholder: '简述...',
    contact_btn: '开始联系',
    brand_identity: '品牌形象 // 架构',
    brand_download: '下载品牌套件.zip',
    spec_dna: '核心颜色 // 核心 DNA',
    spec_palette: '次要颜色 // 身份调色板',
    spec_design: '设计',
    spec_marketing: '营销',
    spec_dev: '编程',
    team_title_prefix: '会见我们的',
    team_title_highlight: '团队',
    team_lead: '首席设计师',
    team_executive: '执行官',
    team_dev: '前端开发',
    team_marketing: '营销',
    team_marketing_exec: '营销主管',
    package_label: '方案',
    package_platforms: '覆盖平台：',
    package_content: '每月内容：',
    package_google: 'Google 管理：',
    package_investment: '广告投入：',
    package_monthly_access: '每月实验室使用权',
    impact: '我们的影响',
    portfolio_tag: '案例研究',
    services_hero_title: '工程 // 解决方案',
    services_hero_desc: '专为市场主导地位设计的高性能数字系统。没有多余的装饰，只有纯粹的建筑效率。',
    services_stack_title: '我们的技术栈',
    services_stack_desc: '尖端工具助力颠覆性成果。',
    services_cta_title: '准备好 <span class="italic">扩展了吗？</span>',
    services_cta_btn: '启动系统同步',
    pkg_web_title: '套餐',
    pkg_web_params: '网页参数',
    pkg_web_1_name: '增长套件',
    pkg_web_2_name: '专业潜力',
    pkg_web_1_feat_1: '5-15个包含博客的定制页面，已针对支付网关进行优化。',
    pkg_web_1_feat_2: '优化的结构，2周内交付。',
    pkg_web_1_feat_3: '每周备份、CDN和优先支持。',
    pkg_web_1_feat_4: '电子商务、服务和潜在客户开发的理想选择。',
    pkg_web_1_feat_5: '企业邮箱、无限SSL和无限制带宽。',
    pkg_web_1_feat_6: 'Hostinger 托管和免费域名（第一年）。',
    pkg_web_1_feat_7: '包含基本的缓存、备份和页面内 SEO 插件。',
    pkg_web_1_feat_8: '正式部署前的实时审核会议。',
    pkg_web_2_feat_1: '超过15个具有高容量架构的定制页面。',
    pkg_web_2_feat_2: '管理多达 5,000 个产品。',
    pkg_web_2_feat_3: '客户面板、暂存环境和专门的 QA。',
    pkg_web_2_feat_4: '重负载流量优化，两周为一个交付周期。',
    pkg_web_2_feat_5: '企业邮箱、无限SSL和无限制带宽。',
    pkg_web_2_feat_6: 'Hostinger 托管和免费域名（第一年）。',
    pkg_web_2_feat_7: '包含基本的缓存、备份和页面内 SEO 插件。',
    pkg_web_2_feat_8: '正式部署前的实时审核会议。',
    pkg_a_name: 'Pro 加速器',
    pkg_a_platforms: 'Instagram, Facebook 和 Google (搜索 + 地图)。',
    pkg_a_content: '16件内容（8个静态, 8个动态）+ 12个互动故事。',
    pkg_a_google: '商家资料优化，回复评论并每月在地图上发布4篇帖子。',
    pkg_a_invest: '$1,500 USD (广告支出)。覆盖：60,280 至 72,140 次印象。',
    pkg_b_name: '全面统领',
    pkg_b_platforms: 'Instagram, Facebook, TikTok 和 Google (搜索 + 地图)。',
    pkg_b_content: '28件内容（12个静态, 16个动态）+ 20个互动故事。',
    pkg_b_google: '高级管理，包含目录更新和本地排名跟踪。',
    pkg_b_invest: '$3,000 USD (广告支出)。覆盖：144,200 至 165,100 次印象。',
    pkg_c_name: '精英全渠道',
    pkg_c_platforms: 'Instagram, Facebook, TikTok, LinkedIn 和 Google (搜索 + 地图)。',
    pkg_c_content: '45 pieces (20 Static, 25 Animated) + 30 Interactive Stories.',
    pkg_c_google: '持续技术审计，针对高竞争查询的高级优化。',
    pkg_c_invest: '$5,000 USD (广告支出)。覆盖：435,700 至 655,700 次印象。',
    about_hero_title: '我们的 // 故事',
    about_hero_desc: '源于打破数字噪音的需要。Drekam Lab 不是一个代理机构，它是一个品牌成功的工程系统。',
    about_origin_title: '受控混乱的起源',
    about_origin_p1: 'Drekam Lab 成立于 2006 年，是对平庸设计的野性回应。我们相信结构必须服从功能，但功能必须主导市场。',
    about_origin_p2: '从地下室的小型代码工作室开始，已演变为全球数字颠覆实验室。',
    about_milestone_1_year: '2006',
    about_milestone_1_text: '系统核心启动。',
    about_milestone_2_year: '2012',
    about_milestone_2_text: '全渠道扩张完成。',
    about_milestone_3_year: '2018',
    about_milestone_3_text: '区域市场统治。',
    about_milestone_4_year: '2024',
    about_milestone_4_text: '全面集成生成式人工智能。',
    about_achievements_title: '系统成就',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>('es');

  const t = (key: string) => {
    const translation = translations[lang][key];
    return translation !== undefined ? translation : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};